import { useCallback, useEffect, useRef, useState } from 'react';
import { analyzeContract, ContractTestingError } from '../lib/contractTesting/client';
import { findSampleContract, SAMPLE_CONTRACTS } from '../lib/contractTesting/fixtures';
import type { AnalysisHistoryEntry, AnalysisResult, GeneratedTestKind } from '../types/contractTesting';

const HISTORY_KEY = 'stellar:contract-testing:history';
const MAX_HISTORY = 10;
const KIND_LABEL: Record<GeneratedTestKind, string> = {
  unit: 'Unit tests',
  property: 'Property-based tests',
  fuzz: 'Fuzz seed corpora',
  regression: 'Regression tests',
};

function loadHistory(): AnalysisHistoryEntry[] {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function saveHistory(history: AnalysisHistoryEntry[]): void {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
  } catch {
    /* storage may be disabled (private browsing, quota) */
  }
}

function historyEntryFrom(result: AnalysisResult): AnalysisHistoryEntry {
  return {
    requestId: result.requestId,
    contractName: result.contract.contractName,
    generatedAt: result.generatedAt,
    findingsCount: result.findings.length,
    criticalFindingsCount: result.findings.filter((f) => f.severity === 'critical').length,
    estimatedPathCoveragePct: result.coverage.estimatedPathCoveragePct,
    estimatedMutationScorePct: result.mutation.estimatedMutationScorePct,
  };
}

function downloadTextFile(filename: string, contents: string, mimeType: string): void {
  const url = URL.createObjectURL(new Blob([contents], { type: mimeType }));
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function useContractTesting() {
  const [source, setSource] = useState('');
  const [contractName, setContractName] = useState('');
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<ContractTestingError | null>(null);
  const [history, setHistory] = useState<AnalysisHistoryEntry[]>(loadHistory);
  const controller = useRef<AbortController | null>(null);

  useEffect(() => () => controller.current?.abort(), []);

  const runAnalysis = useCallback(async () => {
    controller.current?.abort();
    const requestController = new AbortController();
    controller.current = requestController;
    setLoading(true);
    setError(null);
    try {
      const response = await analyzeContract(source, {
        signal: requestController.signal,
        contractName: contractName.trim() || undefined,
      });
      if (requestController.signal.aborted || controller.current !== requestController) return;
      setResult(response.data);
      setHistory((current) => {
        const next = [historyEntryFrom(response.data), ...current].slice(0, MAX_HISTORY);
        saveHistory(next);
        return next;
      });
    } catch (cause) {
      if (!requestController.signal.aborted && controller.current === requestController) {
        setError(
          cause instanceof ContractTestingError
            ? cause
            : new ContractTestingError({ code: 'unavailable', message: 'Unable to analyze contract.', retryable: true })
        );
      }
    } finally {
      if (controller.current === requestController) {
        controller.current = null;
        setLoading(false);
      }
    }
  }, [source, contractName]);

  const loadSample = useCallback((id: string) => {
    const sample = findSampleContract(id);
    if (!sample) return;
    setSource(sample.source);
    setContractName('');
    setError(null);
  }, []);

  const loadFromFile = useCallback(async (file: File) => {
    const text = await file.text();
    setSource(text);
    setError(null);
  }, []);

  const reset = useCallback(() => {
    setResult(null);
    setError(null);
  }, []);

  const downloadTestSuite = useCallback(() => {
    if (!result) return;
    const grouped = (Object.keys(KIND_LABEL) as GeneratedTestKind[])
      .map((kind) => {
        const cases = result.testSuite.testCases.filter((tc) => tc.kind === kind);
        if (cases.length === 0) return '';
        return `// ---- ${KIND_LABEL[kind]} (${cases.length}) ----\n\n${cases.map((tc) => tc.code).join('\n\n')}`;
      })
      .filter(Boolean)
      .join('\n\n');
    const header = `// Generated by Stellar Dev Dashboard — Contract Testing & Verification\n// Contract: ${result.contract.contractName}\n// Generated at: ${result.testSuite.generatedAt}\n// NOTE: fill in the TODOs before relying on these as CI gates.\n\n`;
    downloadTextFile(`${result.contract.contractName}_generated_tests.rs`, header + grouped, 'text/x-rust');
  }, [result]);

  const downloadCiWorkflow = useCallback(() => {
    if (!result) return;
    downloadTextFile(`${result.contract.contractName.toLowerCase()}-contract-tests.yml`, result.ciWorkflowYaml, 'text/yaml');
  }, [result]);

  const downloadReport = useCallback(() => {
    if (!result) return;
    downloadTextFile(
      `${result.contract.contractName}_analysis_report.json`,
      JSON.stringify(result, null, 2),
      'application/json'
    );
  }, [result]);

  return {
    source,
    setSource,
    contractName,
    setContractName,
    result,
    loading,
    error,
    history,
    samples: SAMPLE_CONTRACTS,
    runAnalysis,
    loadSample,
    loadFromFile,
    reset,
    downloadTestSuite,
    downloadCiWorkflow,
    downloadReport,
  };
}
