import type { RecommendationItem } from '../../types/recommendations';

export const RECOMMENDATION_CATALOG: RecommendationItem[] = [
  {
    id: 'account-sdf',
    category: 'account',
    title: 'Stellar Development Foundation',
    description: 'Protocol releases, ecosystem grants, and network operations from the foundation.',
    url: 'https://stellar.org',
    tags: ['protocol', 'grants', 'network', 'builders'],
    goals: ['build', 'learn'],
    risk: 'conservative',
    popularity: 0.98,
    quality: 0.99,
    novelty: 0.16,
    collaborativeSignals: { builder: 0.96, learner: 0.91, payments: 0.65 },
    metadata: { verified: true, sector: 'infrastructure', provider: 'SDF' },
  },
  {
    id: 'account-soroban',
    category: 'account',
    title: 'Soroban Developers',
    description: 'Technical updates and examples for building smart contracts on Stellar.',
    url: 'https://developers.stellar.org/docs/build/smart-contracts',
    tags: ['soroban', 'rust', 'contracts', 'builders'],
    goals: ['build', 'learn'],
    risk: 'balanced',
    popularity: 0.82,
    quality: 0.96,
    novelty: 0.42,
    collaborativeSignals: { builder: 0.99, learner: 0.8, defi: 0.62 },
    metadata: { verified: true, sector: 'developer-tools', provider: 'SDF' },
  },
  {
    id: 'account-moneygram',
    category: 'account',
    title: 'MoneyGram Access',
    description:
      'Discover cash-to-crypto access points and payment integrations powered by Stellar.',
    url: 'https://stellar.org/moneygram',
    tags: ['payments', 'anchor', 'cash', 'remittance'],
    goals: ['payments', 'learn'],
    risk: 'conservative',
    popularity: 0.78,
    quality: 0.91,
    novelty: 0.35,
    collaborativeSignals: { payments: 0.98, learner: 0.63, investor: 0.32 },
    metadata: { verified: true, sector: 'payments', provider: 'MoneyGram' },
  },
  {
    id: 'asset-xlm',
    category: 'asset',
    title: 'Stellar Lumens (XLM)',
    description: 'The native asset used for fees, minimum balances, and network liquidity.',
    url: 'https://developers.stellar.org/docs/learn/fundamentals/stellar-data-structures/assets',
    tags: ['xlm', 'native', 'liquidity', 'fees'],
    goals: ['invest', 'payments', 'learn'],
    risk: 'balanced',
    popularity: 1,
    quality: 0.97,
    novelty: 0.08,
    collaborativeSignals: { investor: 0.92, payments: 0.9, learner: 0.96 },
    metadata: { verified: true, network: 'both', sector: 'native' },
  },
  {
    id: 'asset-usdc',
    category: 'asset',
    title: 'USDC on Stellar',
    description: 'A regulated dollar stablecoin commonly used for payments and treasury workflows.',
    url: 'https://stellar.org/usdc',
    tags: ['usdc', 'stablecoin', 'payments', 'treasury'],
    goals: ['payments', 'defi', 'invest'],
    risk: 'conservative',
    popularity: 0.94,
    quality: 0.96,
    novelty: 0.2,
    collaborativeSignals: { payments: 0.99, investor: 0.78, defi: 0.83 },
    metadata: { verified: true, network: 'mainnet', sector: 'stablecoin', provider: 'Circle' },
  },
  {
    id: 'asset-aqua',
    category: 'asset',
    title: 'AQUA',
    description: 'An ecosystem asset for market-making incentives and liquidity governance.',
    url: 'https://aqua.network',
    tags: ['aqua', 'liquidity', 'dex', 'governance'],
    goals: ['defi', 'invest'],
    risk: 'growth',
    popularity: 0.66,
    quality: 0.72,
    novelty: 0.68,
    collaborativeSignals: { defi: 0.91, investor: 0.7, builder: 0.38 },
    metadata: { network: 'mainnet', sector: 'defi', provider: 'Aquarius' },
  },
  {
    id: 'asset-eurc',
    category: 'asset',
    title: 'EURC on Stellar',
    description:
      'Euro-denominated stable value for cross-border payments and portfolio diversification.',
    url: 'https://www.circle.com/eurc',
    tags: ['eurc', 'stablecoin', 'payments', 'diversification'],
    goals: ['payments', 'invest'],
    risk: 'conservative',
    popularity: 0.59,
    quality: 0.9,
    novelty: 0.61,
    collaborativeSignals: { payments: 0.87, investor: 0.76, defi: 0.54 },
    metadata: { verified: true, network: 'mainnet', sector: 'stablecoin', provider: 'Circle' },
  },
  {
    id: 'contract-blend',
    category: 'contract',
    title: 'Blend Protocol',
    description: 'Explore a Soroban liquidity protocol with lending and borrowing markets.',
    url: 'https://blend.capital',
    tags: ['soroban', 'defi', 'lending', 'liquidity'],
    goals: ['defi', 'build', 'invest'],
    risk: 'growth',
    popularity: 0.77,
    quality: 0.84,
    novelty: 0.7,
    collaborativeSignals: { defi: 0.98, builder: 0.71, investor: 0.7 },
    metadata: { network: 'mainnet', sector: 'defi', securityScore: 86 },
  },
  {
    id: 'contract-token',
    category: 'contract',
    title: 'Soroban Token Example',
    description: 'A reviewed reference contract for learning token interfaces and authorization.',
    url: 'https://developers.stellar.org/docs/build/smart-contracts/example-contracts/token',
    tags: ['soroban', 'token', 'rust', 'security'],
    goals: ['build', 'learn'],
    risk: 'conservative',
    popularity: 0.72,
    quality: 0.95,
    novelty: 0.44,
    collaborativeSignals: { builder: 0.97, learner: 0.9, defi: 0.36 },
    metadata: { verified: true, network: 'both', sector: 'developer-tools', securityScore: 94 },
  },
  {
    id: 'contract-amm',
    category: 'contract',
    title: 'Soroban AMM Example',
    description: 'Learn automated market-maker mechanics from an open reference implementation.',
    url: 'https://developers.stellar.org/docs/build/smart-contracts/example-contracts/amm',
    tags: ['soroban', 'amm', 'dex', 'rust'],
    goals: ['build', 'defi', 'learn'],
    risk: 'balanced',
    popularity: 0.64,
    quality: 0.9,
    novelty: 0.58,
    collaborativeSignals: { builder: 0.91, defi: 0.89, learner: 0.75 },
    metadata: { verified: true, network: 'both', sector: 'defi', securityScore: 90 },
  },
  {
    id: 'service-freighter',
    category: 'service',
    title: 'Freighter Wallet',
    description: 'A browser wallet built for Stellar accounts, assets, and Soroban applications.',
    url: 'https://www.freighter.app',
    tags: ['wallet', 'soroban', 'security', 'builders'],
    goals: ['build', 'defi', 'payments', 'learn'],
    risk: 'conservative',
    popularity: 0.94,
    quality: 0.95,
    novelty: 0.24,
    collaborativeSignals: { builder: 0.96, learner: 0.87, defi: 0.82, payments: 0.7 },
    metadata: { verified: true, network: 'both', sector: 'wallet', provider: 'SDF' },
  },
  {
    id: 'service-lobstr',
    category: 'service',
    title: 'LOBSTR Wallet',
    description: 'A mobile-first wallet for Stellar assets, payments, and account recovery.',
    url: 'https://lobstr.co',
    tags: ['wallet', 'mobile', 'payments', 'assets'],
    goals: ['payments', 'invest', 'learn'],
    risk: 'conservative',
    popularity: 0.88,
    quality: 0.86,
    novelty: 0.3,
    collaborativeSignals: { payments: 0.92, investor: 0.76, learner: 0.7 },
    metadata: { network: 'mainnet', sector: 'wallet', provider: 'LOBSTR' },
  },
  {
    id: 'service-stellar-lab',
    category: 'service',
    title: 'Stellar Laboratory',
    description:
      'Inspect XDR, build transactions, and call Horizon endpoints from a developer workbench.',
    url: 'https://lab.stellar.org',
    tags: ['developer-tools', 'xdr', 'transactions', 'horizon'],
    goals: ['build', 'learn'],
    risk: 'conservative',
    popularity: 0.89,
    quality: 0.98,
    novelty: 0.32,
    collaborativeSignals: { builder: 1, learner: 0.86, payments: 0.35 },
    metadata: { verified: true, network: 'both', sector: 'developer-tools', provider: 'SDF' },
  },
  {
    id: 'service-stellar-expert',
    category: 'service',
    title: 'StellarExpert',
    description: 'Explore accounts, assets, validators, contracts, and network analytics.',
    url: 'https://stellar.expert',
    tags: ['explorer', 'analytics', 'assets', 'contracts'],
    goals: ['invest', 'build', 'learn'],
    risk: 'conservative',
    popularity: 0.91,
    quality: 0.92,
    novelty: 0.28,
    collaborativeSignals: { investor: 0.88, builder: 0.82, learner: 0.78 },
    metadata: { network: 'both', sector: 'analytics', provider: 'OrbitLens' },
  },
  {
    id: 'service-allbridge',
    category: 'service',
    title: 'Allbridge Core',
    description:
      'Bridge supported assets between Stellar and other networks after reviewing route risk.',
    url: 'https://core.allbridge.io',
    tags: ['bridge', 'defi', 'liquidity', 'cross-chain'],
    goals: ['defi', 'invest'],
    risk: 'growth',
    popularity: 0.58,
    quality: 0.73,
    novelty: 0.72,
    collaborativeSignals: { defi: 0.9, investor: 0.61, builder: 0.36 },
    metadata: { network: 'mainnet', sector: 'bridge', provider: 'Allbridge' },
  },
  {
    id: 'service-anchor-platform',
    category: 'service',
    title: 'Anchor Platform',
    description: 'Deploy SEP-compliant deposit, withdrawal, and payment infrastructure.',
    url: 'https://developers.stellar.org/platforms/anchor-platform',
    tags: ['anchor', 'sep', 'payments', 'builders'],
    goals: ['build', 'payments'],
    risk: 'balanced',
    popularity: 0.61,
    quality: 0.94,
    novelty: 0.63,
    collaborativeSignals: { builder: 0.94, payments: 0.96, learner: 0.55 },
    metadata: { verified: true, network: 'both', sector: 'payments', provider: 'SDF' },
  },
];
